default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: n_plus_one_dev

test:
  <<: *default
  database: n_plus_one_test

production:
  <<: *default
  database: n_plus_one_production
